<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PNL-1H883H2" ignored="0" name="Default test" tests="8" failures="0" timestamp="15 Oct 2019 08:25:43 GMT" time="0.392" errors="0">
  <testcase name="@BeforeClass getLogininfo" time="0.0" classname="com.client.xenon.tests.P2PTestCases">
    <failure type="java.lang.ExceptionInInitializerError">
      <![CDATA[java.lang.ExceptionInInitializerError
	at com.client.xenon.operations.P2POperations.<init>(P2POperations.java:30)
	at com.client.fusion.generic.GenericDeclarations.<clinit>(GenericDeclarations.java:11)
	at com.client.xenon.tests.P2PTestCases.getLogininfo(P2PTestCases.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException
	at com.xenon.utility.selenium.Driver.<init>(Driver.java:95)
	at com.xenon.utility.selenium.Driver.getInstance(Driver.java:110)
	at com.xenon.utility.selenium.Framework.<clinit>(Framework.java:6)
	... 28 more
]]>
    </failure>
  </testcase> <!-- @BeforeClass getLogininfo -->
  <testcase name="createNoncatalogRequisition" time="0.002" classname="com.client.xenon.tests.P2PTestCases">
    <skipped/>
  </testcase> <!-- createNoncatalogRequisition -->
  <testcase name="requestPRApproval" time="0.001" classname="com.client.xenon.tests.P2PTestCases">
    <skipped/>
  </testcase> <!-- requestPRApproval -->
  <testcase name="processRequisition" time="0.001" classname="com.client.xenon.tests.P2PTestCases">
    <skipped/>
  </testcase> <!-- processRequisition -->
  <testcase name="receiveItems" time="0.001" classname="com.client.xenon.tests.P2PTestCases">
    <skipped/>
  </testcase> <!-- receiveItems -->
  <testcase name="createInvoice" time="0.001" classname="com.client.xenon.tests.P2PTestCases">
    <skipped/>
  </testcase> <!-- createInvoice -->
  <testcase name="createBatchPaymentForInvoice" time="0.001" classname="com.client.xenon.tests.P2PTestCases">
    <skipped/>
  </testcase> <!-- createBatchPaymentForInvoice -->
  <testcase name="validateAccountingNonPOInvoice" time="0.002" classname="com.client.xenon.tests.P2PTestCases">
    <skipped/>
  </testcase> <!-- validateAccountingNonPOInvoice -->
  <testcase name="createAccounting" time="0.001" classname="com.client.xenon.tests.P2PTestCases">
    <skipped/>
  </testcase> <!-- createAccounting -->
</testsuite> <!-- Default test -->
