<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="8" total="12" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="SALAutoamtion" duration-ms="364889" started-at="2021-01-30T17:17:10Z" finished-at="2021-01-30T17:23:15Z">
    <groups>
    </groups>
    <test name="DemoAutomation" duration-ms="364889" started-at="2021-01-30T17:17:10Z" finished-at="2021-01-30T17:23:15Z">
      <class name="com.client.xenon.tests.AccountToOpportunityFlow">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.client.xenon.tests.AccountToOpportunityFlow@7ba8c737]" name="setup" is-config="true" duration-ms="28918" started-at="2021-01-30T17:16:41Z" finished-at="2021-01-30T17:17:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="createCampaign()[pri:1, instance:com.client.xenon.tests.AccountToOpportunityFlow@7ba8c737]" name="createCampaign" duration-ms="66795" started-at="2021-01-30T17:17:10Z" description="Create campaign Salesforce" finished-at="2021-01-30T17:18:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createCampaign -->
        <test-method status="PASS" signature="createLeadFromCampaign()[pri:2, instance:com.client.xenon.tests.AccountToOpportunityFlow@7ba8c737]" name="createLeadFromCampaign" duration-ms="31909" started-at="2021-01-30T17:18:17Z" description="Create lead from campaign in Salesforce" finished-at="2021-01-30T17:18:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createLeadFromCampaign -->
        <test-method status="FAIL" signature="convertLeadtoOpportunity()[pri:3, instance:com.client.xenon.tests.AccountToOpportunityFlow@7ba8c737]" name="convertLeadtoOpportunity" duration-ms="211993" started-at="2021-01-30T17:18:49Z" description="Convert a lead to create account,contact,opportunity" finished-at="2021-01-30T17:22:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Verification error]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Verification error
	at org.testng.Assert.fail(Assert.java:94)
	at com.client.xenon.operations.PageObjects.convertLeadToOpportunity(PageObjects.java:351)
	at com.client.xenon.tests.AccountToOpportunityFlow.convertLeadtoOpportunity(AccountToOpportunityFlow.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.xenon.core.framework.Xenon.excute(Xenon.java:173)
	at com.client.xenon.framework.DemoAutomation.main(DemoAutomation.java:15)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- convertLeadtoOpportunity -->
        <test-method status="PASS" signature="verificationCheck()[pri:4, instance:com.client.xenon.tests.AccountToOpportunityFlow@7ba8c737]" name="verificationCheck" duration-ms="51693" started-at="2021-01-30T17:22:23Z" description="Verification check" finished-at="2021-01-30T17:23:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verificationCheck -->
        <test-method status="PASS" signature="cleanup()[pri:0, instance:com.client.xenon.tests.AccountToOpportunityFlow@7ba8c737]" name="cleanup" is-config="true" duration-ms="0" started-at="2021-01-30T17:23:16Z" finished-at="2021-01-30T17:23:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanup -->
      </class> <!-- com.client.xenon.tests.AccountToOpportunityFlow -->
    </test> <!-- DemoAutomation -->
  </suite> <!-- SALAutoamtion -->
</testng-results>
